<?php
namespace Modules\Car\Controllers;

use App\Http\Controllers\Controller;
use Modules\Car\Models\Car;
use Modules\Car\Models\CarPickupLocation;
use Illuminate\Http\Request;
use Modules\Location\Models\Location;
use Modules\Review\Models\Review;
use Modules\Core\Models\Attributes;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Arr;
use Carbon\Carbon;

class CarController extends Controller
{
    protected $carClass;
    protected $locationClass;
    public function __construct(Car $carClass, Location $locationClass)
    {
        $this->carClass = $carClass;
        $this->locationClass = $locationClass;
    }

    public function callAction($method, $parameters)
    {
        if(!$this->carClass::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
    public function index(Request $request)
    {

        $layout = setting_item("car_layout_search", 'normal');
        if ($request->query('_layout')) {
            $layout = $request->query('_layout');
        }
        $is_ajax = $request->query('_ajax');
        $for_map = $request->query('_map',$layout === 'map');

        if(!empty($request->query('limit'))){
            $limit = $request->query('limit');
        }else{
            $limit = !empty(setting_item("car_page_limit_item"))? setting_item("car_page_limit_item") : 9;

        }
        $input = $request->input();
        $pickupPayload = $request->input('pickup');
        if (is_string($pickupPayload)) {
            $decodedPickup = json_decode($pickupPayload, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                $pickupPayload = $decodedPickup;
            }
        }
        if (!is_array($pickupPayload)) {
            $pickupPayload = [];
        }

        $pickupLocationId = Arr::get($pickupPayload, 'id') ?? $request->input('pickup_location_id');
        $selectedPickupLocation = null;
        if ($pickupLocationId) {
            $selectedPickupLocation = CarPickupLocation::with('car')->find($pickupLocationId);
            if ($selectedPickupLocation && $selectedPickupLocation->is_active) {
                $pickupPayload = array_merge($selectedPickupLocation->toFrontendArray(), $pickupPayload);
                $pickupPayload['source'] = Arr::get($pickupPayload, 'source', 'backend');
                $input['pickup_location_id'] = $pickupLocationId;
            } else {
                $selectedPickupLocation = null;
            }
        }
        $input['pickup'] = $pickupPayload;
        $transferDatetime = Arr::get($input, 'transfer_datetime');
        if (!$transferDatetime) {
            $fallbackDate = Arr::get($input, 'transfer_date');
            $fallbackTime = Arr::get($input, 'transfer_time');
            if ($fallbackDate && $fallbackTime) {
                try {
                    $transferDatetime = Carbon::parse($fallbackDate . ' ' . $fallbackTime, 'Asia/Tbilisi')
                        ->setTimezone('Asia/Tbilisi')
                        ->toIso8601String();
                    $input['transfer_datetime'] = $transferDatetime;
                    $request->merge(['transfer_datetime' => $transferDatetime]);
                } catch (\Exception $exception) {
                    $transferDatetime = null;
                }
            }
        }

        $query = $this->carClass->search($input);

        $dropoff = Arr::get($input, 'dropoff', []);
        if (is_string($dropoff)) {
            $decodedDropoff = json_decode($dropoff, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                $dropoff = $decodedDropoff;
            }
        }
        if (!is_array($dropoff)) {
            $dropoff = [];
        }
        $transferDate = null;
        if ($transferDatetime) {
            try {
                $transferDate = Carbon::parse($transferDatetime, 'Asia/Tbilisi')->setTimezone('Asia/Tbilisi')->toDateString();
            } catch (\Exception $exception) {
                $transferDate = null;
            }
        }
        $pickupLat = Arr::has($pickupPayload, 'lat') && is_numeric($pickupPayload['lat']) ? (float) $pickupPayload['lat'] : null;
        $pickupLng = Arr::has($pickupPayload, 'lng') && is_numeric($pickupPayload['lng']) ? (float) $pickupPayload['lng'] : null;
        $dropoffLat = Arr::has($dropoff, 'lat') && is_numeric($dropoff['lat']) ? (float) $dropoff['lat'] : null;
        $dropoffLng = Arr::has($dropoff, 'lng') && is_numeric($dropoff['lng']) ? (float) $dropoff['lng'] : null;
        $requiresTransfer = $pickupLat !== null && $pickupLng !== null && $dropoffLat !== null && $dropoffLng !== null;
        $transferDistanceKm = null;
        $transferDurationMin = null;
        if ($requiresTransfer) {
            $metrics = $this->carClass::resolveRouteMetrics($pickupPayload, $dropoff);
            $transferDistanceKm = $metrics['distance_km'];
            $transferDurationMin = $metrics['duration_min'];
            $rows = $query->get();
            $filtered = $rows->filter(function ($car) use ($selectedPickupLocation, $pickupLocationId, $pickupPayload, $dropoff, $transferDistanceKm, $transferDurationMin, $transferDate, $transferDatetime) {
                $pickupLocation = null;
                if ($selectedPickupLocation && $selectedPickupLocation->car_id === $car->id) {
                    $pickupLocation = $selectedPickupLocation;
                } elseif ($pickupLocationId) {
                    $pickupLocation = $car->pickupLocations->firstWhere('id', (int) $pickupLocationId);
                }

                return $car->applyTransferContext(
                    $pickupLocation,
                    $pickupPayload,
                    $dropoff,
                    $transferDistanceKm,
                    $transferDurationMin,
                    $transferDate,
                    $transferDatetime
                );
            })->values();
            $currentPage = LengthAwarePaginator::resolveCurrentPage();
            $list = new LengthAwarePaginator(
                $filtered->forPage($currentPage, $limit)->values(),
                $filtered->count(),
                $limit,
                $currentPage,
                ['path' => $request->url(), 'query' => $request->query()]
            );
        } else {
            $list = $query->paginate($limit);
        }
        $list->appends($request->query());
        $markers = [];
        if (!empty($list) and $for_map) {
            foreach ($list as $row) {
                $markers[] = [
                    "id"      => $row->id,
                    "title"   => $row->title,
                    "lat"     => (float)$row->map_lat,
                    "lng"     => (float)$row->map_lng,
                    "gallery" => $row->getGallery(true),
                    "infobox" => view('Car::frontend.layouts.search.loop-grid', ['row' => $row,'disable_lazyload'=>1,'wrap_class'=>'infobox-item'])->render(),
                    'marker' => get_file_url(setting_item("car_icon_marker_map"),'full') ?? url('images/icons/png/pin.png'),
                ];
            }
        }
        $data = [
            'rows' => $list,
            'layout'=>$layout
        ];
        if ($is_ajax) {
            return $this->sendSuccess([
                "markers" => $markers,
                'fragments'=>[
                    '.ajax-search-result'=>view('Car::frontend.ajax.search-result'.($for_map ? '-map' : ''), $data)->render(),
                    '.result-count'=>$list->total() ? ($list->total() > 1 ? __(":count cars found",['count'=>$list->total()]) : __(":count car found",['count'=>$list->total()])) : '',
                    '.count-string'=> $list->total() ? __("Showing :from - :to of :total Cars",["from"=>$list->firstItem(),"to"=>$list->lastItem(),"total"=>$list->total()]) : ''
                ]
            ]);
        }
        $data = [
            'rows'               => $list,
            'list_location'      => $this->locationClass::where('status', 'publish')->limit(1000)->with(['translation'])->get()->toTree(),
            'car_min_max_price' => $this->carClass::getMinMaxPrice(),
            'markers'            => $markers,
            "blank" => setting_item('search_open_tab') == "current_tab" ? 0 : 1 ,
            "seo_meta"           => $this->carClass::getSeoMetaForPageList(),
            'transfer_distance_km' => $transferDistanceKm,
            'transfer_duration_min' => $transferDurationMin,
            'pickup_locations' => $this->carClass::getAvailablePickupLocations(),
            'selected_pickup_location' => $selectedPickupLocation,
            'selected_pickup_location_id' => $selectedPickupLocation?->id ?? ($pickupLocationId ?: null),
            'selected_dropoff' => $dropoff,
            'selected_pickup_payload' => $pickupPayload,
        ];
        $data['layout'] = $layout;
        $data['attributes'] = Attributes::where('service', 'car')->orderBy("position","desc")->with(['terms'=>function($query){
            $query->withCount('car');
        },'translation'])->get();

        if ($layout == "map") {
            $data['body_class'] = 'has-search-map';
            $data['html_class'] = 'full-page';
            return view('Car::frontend.search-map', $data);
        }
        return view('Car::frontend.search', $data);
    }

    public function pickupLocations(Request $request)
    {
        $query = CarPickupLocation::query()
            ->with(['car:id,title,status'])
            ->whereHas('car', function ($builder) {
                $builder->where('status', 'publish');
            })
            ->active();

        if ($request->filled('car_id')) {
            $carIds = Arr::wrap($request->input('car_id'));
            $query->whereIn('car_id', array_filter($carIds));
        }

        $locations = $query
            ->orderBy('name')
            ->get()
            ->map(function (CarPickupLocation $location) {
                $payload = $location->toFrontendArray();
                $payload['car_title'] = $location->car?->title;
                $payload['label'] = $payload['name'] . (!empty($payload['car_title']) ? ' — ' . $payload['car_title'] : '');
                return $payload;
            })
            ->values();

        return $this->sendSuccess(['data' => $locations]);
    }

    public function detail(Request $request, $slug)
    {
        $row = $this->carClass::where('slug', $slug)->with(['location','translation','hasWishList','pickupLocations.car'])->first();
        if ( empty($row) or !$row->hasPermissionDetailView()) {
            return redirect('/');
        }
        $translation = $row->translate();
        $car_related = [];
        $location_id = $row->location_id;
        if (!empty($location_id)) {
            $car_related = $this->carClass::where('location_id', $location_id)->where("status", "publish")->take($this->limitRelated ?? 4)->whereNotIn('id', [$row->id])->with(['location','translation','hasWishList'])->get();
        }
        $review_list = $row->getReviewList();

        $pickupPayload = $request->input('pickup');
        if (is_string($pickupPayload)) {
            $decodedPickup = json_decode($pickupPayload, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                $pickupPayload = $decodedPickup;
            }
        }
        if (!is_array($pickupPayload)) {
            $pickupPayload = [];
        }

        $selectedPickupLocation = null;
        $pickupLocationId = Arr::get($pickupPayload, 'id') ?? $request->input('pickup_location_id');
        if ($pickupLocationId) {
            $selectedPickupLocation = $row->pickupLocations()->where('id', $pickupLocationId)->where('is_active', true)->first();
            if ($selectedPickupLocation) {
                $pickupPayload = array_merge($selectedPickupLocation->toFrontendArray(), $pickupPayload);
                $pickupPayload['source'] = Arr::get($pickupPayload, 'source', 'backend');
            }
        }

        $transferDatetimeRaw = $request->input('transfer_datetime');
        $transferDatetimeDisplay = null;
        $transferDate = null;
        if ($transferDatetimeRaw) {
            try {
                $transferDatetimeDisplay = Carbon::parse($transferDatetimeRaw, 'Asia/Tbilisi')->setTimezone('Asia/Tbilisi');
                $transferDate = $transferDatetimeDisplay->toDateString();
            } catch (\Exception $exception) {
                $transferDatetimeDisplay = null;
                $transferDate = null;
            }
        }

        $dropoff = $request->input('dropoff', []);
        if (is_string($dropoff)) {
            $decodedDropoff = json_decode($dropoff, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                $dropoff = $decodedDropoff;
            }
        }
        if (!is_array($dropoff)) {
            $dropoff = [];
        }

        $pickupLat = isset($pickupPayload['lat']) && is_numeric($pickupPayload['lat']) ? (float) $pickupPayload['lat'] : null;
        $pickupLng = isset($pickupPayload['lng']) && is_numeric($pickupPayload['lng']) ? (float) $pickupPayload['lng'] : null;
        $dropoffLat = isset($dropoff['lat']) && is_numeric($dropoff['lat']) ? (float) $dropoff['lat'] : null;
        $dropoffLng = isset($dropoff['lng']) && is_numeric($dropoff['lng']) ? (float) $dropoff['lng'] : null;
        if ($pickupLat !== null && $pickupLng !== null && $dropoffLat !== null && $dropoffLng !== null) {
            $metrics = $this->carClass::resolveRouteMetrics(array_merge($pickupPayload, ['lat' => $pickupLat, 'lng' => $pickupLng]), $dropoff);
            $routePickupLocation = $selectedPickupLocation && $selectedPickupLocation->car_id === $row->id ? $selectedPickupLocation : null;
            $row->applyTransferContext(
                $routePickupLocation,
                array_merge($pickupPayload, ['lat' => $pickupLat, 'lng' => $pickupLng]),
                $dropoff,
                $metrics['distance_km'],
                $metrics['duration_min'],
                $transferDate,
                $transferDatetimeRaw
            );
        }

        $data = [
            'row'          => $row,
            'translation'       => $translation,
            'car_related' => $car_related,
            'booking_data' => $row->getBookingData(),
            'review_list'  => $review_list,
            'seo_meta'  => $row->getSeoMetaWithTranslation(app()->getLocale(),$translation),
            'body_class'=>'is_single',
            'pickup_location' => $selectedPickupLocation,
            'pickup_payload' => $pickupPayload,
            'dropoff' => $dropoff,
            'transfer_datetime_value' => $transferDatetimeRaw,
            'transfer_datetime_display' => $transferDatetimeDisplay,
            'transfer_distance_km' => $row->transfer_distance_km,
            'pickup_locations' => $row->pickupLocations,
            'breadcrumbs'       => [
                [
                    'name'  => __('Car'),
                    'url'  => route('car.search'),
                ],
            ],
        ];
        $data['breadcrumbs'] = array_merge($data['breadcrumbs'],$row->locationBreadcrumbs());
        $data['breadcrumbs'][] = [
            'name'  => $translation->title,
            'class' => 'active'
        ];
        $this->setActiveMenu($row);
        return view('Car::frontend.detail', $data);
    }
}
