<?php
namespace Modules\Car\Controllers;

use App\Http\Controllers\Controller;
use Modules\Car\Models\Car;
use Modules\Car\Models\CarPickupLocation;
use Modules\Car\Models\TransferLocation;
use Illuminate\Http\Request;
use Modules\Location\Models\Location;
use Modules\Review\Models\Review;
use Modules\Core\Models\Attributes;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Arr;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Modules\Booking\Models\Booking;

class CarController extends Controller
{
    protected $carClass;
    protected $locationClass;
    public function __construct(Car $carClass, Location $locationClass)
    {
        $this->carClass = $carClass;
        $this->locationClass = $locationClass;
    }

    public function callAction($method, $parameters)
    {
        if(!$this->carClass::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
    public function index(Request $request)
    {

        $layout = setting_item("car_layout_search", 'normal');
        if ($request->query('_layout')) {
            $layout = $request->query('_layout');
        }
        $is_ajax = $request->query('_ajax');
        $for_map = $request->query('_map',$layout === 'map');

        if(!empty($request->query('limit'))){
            $limit = $request->query('limit');
        }else{
            $limit = !empty(setting_item("car_page_limit_item"))? setting_item("car_page_limit_item") : 9;

        }
        $input = $request->input();
        $pickupPayload = $request->input('pickup');
        if (is_string($pickupPayload)) {
            $decodedPickup = json_decode($pickupPayload, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                $pickupPayload = $decodedPickup;
            }
        }
        if (!is_array($pickupPayload)) {
            $pickupPayload = [];
        }

        $pickupLocationId = Arr::get($pickupPayload, 'id') ?? $request->input('pickup_location_id');
        $selectedPickupLocation = null;
        if ($pickupLocationId) {
            $selectedPickupLocation = TransferLocation::find($pickupLocationId);
            if ($selectedPickupLocation && $selectedPickupLocation->is_active) {
                $pickupPayload = array_merge($selectedPickupLocation->toFrontendArray(), $pickupPayload);
                $pickupPayload['source'] = Arr::get($pickupPayload, 'source', 'backend');
                $input['pickup_location_id'] = $pickupLocationId;
            } else {
                $selectedPickupLocation = null;
            }
        }
        $input['pickup'] = $pickupPayload;
        $transferDatetime = Arr::get($input, 'transfer_datetime');
        if (!$transferDatetime) {
            $fallbackDate = Arr::get($input, 'transfer_date');
            $fallbackTime = Arr::get($input, 'transfer_time');
            if ($fallbackDate && $fallbackTime) {
                try {
                    $transferDatetime = Carbon::parse($fallbackDate . ' ' . $fallbackTime, 'Asia/Tbilisi')
                        ->setTimezone('Asia/Tbilisi')
                        ->toIso8601String();
                    $input['transfer_datetime'] = $transferDatetime;
                    $request->merge(['transfer_datetime' => $transferDatetime]);
                } catch (\Exception $exception) {
                    $transferDatetime = null;
                }
            }
        }

        $query = $this->carClass->search($input);

        $dropoff = Arr::get($input, 'dropoff', []);
        if (is_string($dropoff)) {
            $decodedDropoff = json_decode($dropoff, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                $dropoff = $decodedDropoff;
            }
        }
        if (!is_array($dropoff)) {
            $dropoff = [];
        }

        $userPickup = $request->input('user_pickup', []);
        if (is_string($userPickup)) {
            $decodedUserPickup = json_decode($userPickup, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                $userPickup = $decodedUserPickup;
            }
        }
        if (!is_array($userPickup)) {
            $userPickup = [];
        }
        $input['user_pickup'] = $userPickup;
        $transferDate = null;
        if ($transferDatetime) {
            try {
                $transferDate = Carbon::parse($transferDatetime, 'Asia/Tbilisi')->setTimezone('Asia/Tbilisi')->toDateString();
            } catch (\Exception $exception) {
                $transferDate = null;
            }
        }
        $pickupLat = Arr::has($pickupPayload, 'lat') && is_numeric($pickupPayload['lat']) ? (float) $pickupPayload['lat'] : null;
        $pickupLng = Arr::has($pickupPayload, 'lng') && is_numeric($pickupPayload['lng']) ? (float) $pickupPayload['lng'] : null;
        $dropoffLat = Arr::has($dropoff, 'lat') && is_numeric($dropoff['lat']) ? (float) $dropoff['lat'] : null;
        $dropoffLng = Arr::has($dropoff, 'lng') && is_numeric($dropoff['lng']) ? (float) $dropoff['lng'] : null;
        $userPickupLat = Arr::has($userPickup, 'lat') && is_numeric($userPickup['lat']) ? (float) $userPickup['lat'] : null;
        $userPickupLng = Arr::has($userPickup, 'lng') && is_numeric($userPickup['lng']) ? (float) $userPickup['lng'] : null;
        $requiresTransfer = $pickupLat !== null && $pickupLng !== null && $dropoffLat !== null && $dropoffLng !== null;
        $transferDistanceKm = null;
        $transferDurationMin = null;
        $userPickupNormalized = null;
        if ($userPickupLat !== null && $userPickupLng !== null) {
            $userPickupNormalized = array_merge($userPickup, [
                'lat' => $userPickupLat,
                'lng' => $userPickupLng,
            ]);
        }
        if ($requiresTransfer) {
            $metrics = $this->carClass::resolveRouteMetrics($pickupPayload, $dropoff);
            $transferDistanceKm = $metrics['distance_km'];
            $transferDurationMin = $metrics['duration_min'];
            $passengers = (int) ($input['passengers'] ?? $input['number'] ?? $input['adults'] ?? 1);
            if ($passengers < 1) {
                $passengers = 1;
            }
            $userRouteMetrics = null;
            if ($userPickupNormalized) {
                $userRouteMetrics = $this->carClass::resolveRouteMetrics($userPickupNormalized, $dropoff);
            }
            $rows = $query->get();
            $filtered = $rows->filter(function ($car) use ($selectedPickupLocation, $pickupLocationId, $pickupPayload, $dropoff, $transferDistanceKm, $transferDurationMin, $transferDate, $transferDatetime, $passengers, $userPickupNormalized, $userRouteMetrics) {
                $pickupLocation = null;

                $userPayload = $userPickupNormalized;
                if ($car->pricing_mode !== 'fixed' && !$userPayload) {
                    $car->clearTransferContext();
                    return true;
                }

                $userPayload = $userPickupNormalized;
                if ($car->pricing_mode !== 'fixed' && !$userPayload) {
                    $car->clearTransferContext();
                    return true;
                }

                $userDistance = $userRouteMetrics['distance_km'] ?? null;
                $userDuration = $userRouteMetrics['duration_min'] ?? null;

                return $car->applyTransferContext(
                    $pickupLocation,
                    $pickupPayload,
                    $dropoff,
                    $transferDistanceKm,
                    $transferDurationMin,
                    $transferDate,
                    $transferDatetime,
                    $passengers,
                    $userPayload,
                    $userDistance,
                    $userDuration
                );
            })->values();
            $currentPage = LengthAwarePaginator::resolveCurrentPage();
            $list = new LengthAwarePaginator(
                $filtered->forPage($currentPage, $limit)->values(),
                $filtered->count(),
                $limit,
                $currentPage,
                ['path' => $request->url(), 'query' => $request->query()]
            );
        } else {
            $list = $query->paginate($limit);
        }
        $list->appends($request->query());
        $markers = [];
        if (!empty($list) and $for_map) {
            foreach ($list as $row) {
                $markers[] = [
                    "id"      => $row->id,
                    "title"   => $row->title,
                    "lat"     => (float)$row->map_lat,
                    "lng"     => (float)$row->map_lng,
                    "gallery" => $row->getGallery(true),
                    "infobox" => view('Car::frontend.layouts.search.loop-grid', ['row' => $row,'disable_lazyload'=>1,'wrap_class'=>'infobox-item'])->render(),
                    'marker' => get_file_url(setting_item("car_icon_marker_map"),'full') ?? url('images/icons/png/pin.png'),
                ];
            }
        }
        $data = [
            'rows' => $list,
            'layout'=>$layout
        ];
        if ($is_ajax) {
            return $this->sendSuccess([
                "markers" => $markers,
                'fragments'=>[
                    '.ajax-search-result'=>view('Car::frontend.ajax.search-result'.($for_map ? '-map' : ''), $data)->render(),
                    '.result-count'=>$list->total() ? ($list->total() > 1 ? __(":count cars found",['count'=>$list->total()]) : __(":count car found",['count'=>$list->total()])) : '',
                    '.count-string'=> $list->total() ? __("Showing :from - :to of :total Cars",["from"=>$list->firstItem(),"to"=>$list->lastItem(),"total"=>$list->total()]) : ''
                ]
            ]);
        }
        $data = [
            'rows'               => $list,
            'list_location'      => $this->locationClass::where('status', 'publish')->limit(1000)->with(['translation'])->get()->toTree(),
            'car_min_max_price' => $this->carClass::getMinMaxPrice(),
            'markers'            => $markers,
            "blank" => setting_item('search_open_tab') == "current_tab" ? 0 : 1 ,
            "seo_meta"           => $this->carClass::getSeoMetaForPageList(),
            'transfer_distance_km' => $transferDistanceKm,
            'transfer_duration_min' => $transferDurationMin,
            'pickup_locations' => $this->carClass::getAvailablePickupLocations(),
            'selected_pickup_location' => $selectedPickupLocation,
            'selected_pickup_location_id' => $selectedPickupLocation?->id ?? ($pickupLocationId ?: null),
            'selected_dropoff' => $dropoff,
            'selected_pickup_payload' => $pickupPayload,
            'selected_user_pickup' => $userPickup,
            'selected_user_pickup_payload' => $userPickupNormalized,
        ];
        $data['layout'] = $layout;
        $data['attributes'] = Attributes::where('service', 'car')->orderBy("position","desc")->with(['terms'=>function($query){
            $query->withCount('car');
        },'translation'])->get();

        if ($layout == "map") {
            $data['body_class'] = 'has-search-map';
            $data['html_class'] = 'full-page';
            return view('Car::frontend.search-map', $data);
        }
        return view('Car::frontend.search', $data);
    }

    public function pickupLocations(Request $request)
    {
        $query = CarPickupLocation::query()
            ->with(['car:id,title,status'])
            ->active()
            ->where(function ($builder) {
                $builder->whereHas('car', function ($carQuery) {
                    $carQuery->where('status', 'publish');
                })->orWhere(function ($inner) {
                    $inner->whereNull('car_id')->whereNull('vendor_id');
                });
            });

        if ($request->filled('car_id')) {
            $carIds = Arr::wrap($request->input('car_id'));
            $carIds = array_values(array_filter(array_map(function ($value) {
                return is_numeric($value) ? (int) $value : null;
            }, $carIds)));

            if (!empty($carIds)) {
                $cars = Car::query()->select(['id', 'author_id', 'status'])->whereIn('id', $carIds)->get();
                $vendorIds = $cars->pluck('author_id')->filter()->unique()->values()->all();

                $query->where(function ($builder) use ($carIds, $vendorIds) {
                    $builder->whereIn('car_id', $carIds)
                        ->orWhere(function ($inner) use ($vendorIds) {
                            $inner->whereNull('car_id');

                            if (!empty($vendorIds)) {
                                $inner->where(function ($vendorClause) use ($vendorIds) {
                                    $vendorClause->whereNull('vendor_id')
                                        ->orWhereIn('vendor_id', $vendorIds);
                                });
                            } else {
                                $inner->whereNull('vendor_id');
                            }
                        });
                });
            }
        }

        if ($request->filled('vendor_id')) {
            $query->where('vendor_id', $request->input('vendor_id'));
        }

        if ($search = $request->query('q', $request->query('s'))) {
            $query->where(function ($builder) use ($search) {
                $builder->where('name', 'LIKE', '%' . $search . '%')
                    ->orWhere('address', 'LIKE', '%' . $search . '%')
                    ->orWhere('service_center_name', 'LIKE', '%' . $search . '%');
            });
        }

        $locations = $query
            ->orderByRaw("CASE WHEN name IS NULL OR name = '' THEN 1 ELSE 0 END")
            ->orderByRaw("CASE WHEN address IS NULL OR address = '' THEN 1 ELSE 0 END")
            ->orderBy('name')
            ->orderBy('address')
            ->orderBy('id')
            ->get()
            ->map(function (CarPickupLocation $location) {
                $payload = $location->toFrontendArray();
                $payload['car_title'] = $location->car?->title;
                $displayLabel = $payload['display_name'] ?? $payload['name'] ?? $payload['address'] ?? '';
                $payload['label'] = $displayLabel . (!empty($payload['car_title']) ? ' — ' . $payload['car_title'] : '');
                return $payload;
            })
            ->filter(function (array $payload) {
                return isset($payload['lat'], $payload['lng'])
                    && is_numeric($payload['lat'])
                    && is_numeric($payload['lng']);
            })
            ->values();

        return $this->sendSuccess(['data' => $locations]);
    }

    public function availability(Request $request, Car $car)
    {
        if ($car->status !== 'publish') {
            return $this->sendError(__('transfers.booking.price_details_unavailable'), [], 404);
        }

        $dateParam = $request->query('date');
        $startParam = $request->query('start', $dateParam);
        $endParam = $request->query('end', $dateParam);

        try {
            $startDate = $startParam
                ? Carbon::parse($startParam, 'Asia/Tbilisi')->startOfDay()
                : Carbon::now('Asia/Tbilisi')->startOfDay();
        } catch (\Exception $exception) {
            return $this->sendError(__('transfers.booking.availability_invalid_date'), [], 422);
        }

        try {
            $endDate = $endParam
                ? Carbon::parse($endParam, 'Asia/Tbilisi')->endOfDay()
                : $startDate->copy()->endOfDay();
        } catch (\Exception $exception) {
            $endDate = $startDate->copy()->endOfDay();
        }

        if ($endDate->lt($startDate)) {
            $endDate = $startDate->copy()->endOfDay();
        }

        $maxRangeDays = 60;
        if ($endDate->diffInDays($startDate) > $maxRangeDays) {
            $endDate = $startDate->copy()->addDays($maxRangeDays)->endOfDay();
        }

        $passengers = (int) $request->query('passengers', 1);
        if ($passengers < 1) {
            $passengers = 1;
        }
        $maxPassengers = (int) ($car->number ?? 0);
        if ($maxPassengers > 0 && $passengers > $maxPassengers) {
            $passengers = $maxPassengers;
        }

        $pickupPayload = [];
        $pickupLocation = null;
        $pickupLocationId = $request->query('pickup_location_id');
        if ($pickupLocationId) {
            $pickupLocation = CarPickupLocation::query()
                ->availableForCar($car)
                ->where('id', $pickupLocationId)
                ->first();
            if ($pickupLocation) {
                $pickupPayload = $pickupLocation->toFrontendArray();
                $pickupPayload['source'] = Arr::get($pickupPayload, 'source', 'backend');
            } else {
                $pickupLocation = null;
            }
        }

        $pickupLat = $request->query('pickup_lat');
        $pickupLng = $request->query('pickup_lng');
        if (is_numeric($pickupLat) && is_numeric($pickupLng)) {
            $pickupPayload = array_merge($pickupPayload, [
                'lat' => (float) $pickupLat,
                'lng' => (float) $pickupLng,
            ]);
        }

        $dropoffPayload = [];
        $dropoffLat = $request->query('dropoff_lat');
        $dropoffLng = $request->query('dropoff_lng');
        $dropoffPlaceId = $request->query('dropoff_place_id');
        if (is_numeric($dropoffLat) && is_numeric($dropoffLng) && $dropoffPlaceId) {
            $dropoffPayload = [
                'lat' => (float) $dropoffLat,
                'lng' => (float) $dropoffLng,
                'place_id' => $dropoffPlaceId,
            ];
        }

        $routeMetrics = null;
        $pickupForMetrics = $pickupPayload;
        if ($pickupLocation) {
            $pickupForMetrics = array_merge($pickupLocation->toFrontendArray(), $pickupForMetrics);
        }
        if (!empty($pickupForMetrics['lat']) && !empty($pickupForMetrics['lng']) && !empty($dropoffPayload)) {
            $routeMetrics = $car::resolveRouteMetrics($pickupForMetrics, $dropoffPayload);
        }

        $userPickupPayload = $request->query('user_pickup', []);
        if (is_string($userPickupPayload)) {
            $decodedUserPickup = json_decode($userPickupPayload, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                $userPickupPayload = $decodedUserPickup;
            }
        }
        if (!is_array($userPickupPayload)) {
            $userPickupPayload = [];
        }
        $userPickupLat = Arr::get($userPickupPayload, 'lat');
        $userPickupLng = Arr::get($userPickupPayload, 'lng');
        $normalizedUserPickup = null;
        if (is_numeric($userPickupLat) && is_numeric($userPickupLng)) {
            $normalizedUserPickup = array_merge($userPickupPayload, [
                'lat' => (float) $userPickupLat,
                'lng' => (float) $userPickupLng,
            ]);
        }
        $userRouteMetrics = null;
        if ($normalizedUserPickup && !empty($dropoffPayload)) {
            $userRouteMetrics = $car::resolveRouteMetrics($normalizedUserPickup, $dropoffPayload);
        }

        $dates = [];
        $cursor = $startDate->copy();
        while ($cursor->lte($endDate)) {
            $dailyAvailability = $this->buildAvailabilityForDate(
                $car,
                $cursor->copy(),
                $passengers,
                $pickupLocation,
                $pickupPayload,
                $dropoffPayload,
                $routeMetrics,
                $normalizedUserPickup,
                $userRouteMetrics
            );
            if (empty($dailyAvailability)) {
                $cursor->addDay()->startOfDay();
                continue;
            }
            $dates[] = $dailyAvailability;
            $cursor->addDay()->startOfDay();
        }

        return $this->sendSuccess([
            'data' => [
                'dates' => $dates,
            ],
        ]);
    }

    protected function buildAvailabilityForDate(Car $car, Carbon $date, int $passengers, ?CarPickupLocation $pickupLocation = null, array $pickupPayload = [], array $dropoff = [], ?array $routeMetrics = null, ?array $userPickup = null, ?array $userRouteMetrics = null): array
    {
        $start = $date->copy()->startOfDay();
        $end = $date->copy()->endOfDay();
        $dailyStart = $this->parseTimeOfDay($car->transfer_time_start, $date);
        $dailyEnd = $this->parseTimeOfDay($car->transfer_time_end, $date);
        if ($dailyStart && $dailyEnd && $dailyEnd->lt($dailyStart)) {
            return [];
        }

        $availabilityCar = clone $car;
        $available = $availabilityCar->isAvailableInRanges(
            $start->format('Y-m-d H:i:s'),
            $end->format('Y-m-d H:i:s'),
            $passengers
        );

        $note = null;

        $pickupLat = Arr::get($pickupPayload, 'lat');
        $pickupLng = Arr::get($pickupPayload, 'lng');
        $dropoffLat = Arr::get($dropoff, 'lat');
        $dropoffLng = Arr::get($dropoff, 'lng');
        $dropoffPlaceId = Arr::get($dropoff, 'place_id');
        $userPickupLat = Arr::get($userPickup, 'lat');
        $userPickupLng = Arr::get($userPickup, 'lng');

        $hasRouteContext = $available
            && is_numeric($pickupLat)
            && is_numeric($pickupLng)
            && is_numeric($dropoffLat)
            && is_numeric($dropoffLng)
            && !empty($dropoffPlaceId);

        if ($available && $hasRouteContext) {
            $normalizedPickup = array_merge($pickupLocation?->toFrontendArray() ?? [], $pickupPayload, [
                'lat' => (float) $pickupLat,
                'lng' => (float) $pickupLng,
            ]);
            $normalizedDropoff = array_merge($dropoff, [
                'lat' => (float) $dropoffLat,
                'lng' => (float) $dropoffLng,
            ]);

            $normalizedUserPickup = null;
            if (is_numeric($userPickupLat) && is_numeric($userPickupLng)) {
                $normalizedUserPickup = array_merge($userPickup ?? [], [
                    'lat' => (float) $userPickupLat,
                    'lng' => (float) $userPickupLng,
                ]);
            }

            $routeDistance = $routeMetrics['distance_km'] ?? null;
            $routeDuration = $routeMetrics['duration_min'] ?? null;
            $userDistance = $userRouteMetrics['distance_km'] ?? null;
            $userDuration = $userRouteMetrics['duration_min'] ?? null;

            $pricingMode = $car->pricing_mode ?: 'per_km';
            if ($pricingMode !== 'fixed' && !$normalizedUserPickup) {
                $available = false;
                $note = __('transfers.booking.pickup_required');
            }

            if ($available) {
                if (!$availabilityCar->applyTransferContext(
                    $pickupLocation,
                    $normalizedPickup,
                    $normalizedDropoff,
                    $routeDistance,
                    $routeDuration,
                    $date->toDateString(),
                    null,
                    $passengers,
                    $normalizedUserPickup,
                    $userDistance,
                    $userDuration
                )) {
                    $available = false;
                    $note = __('transfers.booking.price_details_unavailable');
                }
            }
        }

        if (!$available && !$note) {
            $note = __('transfers.booking.availability_unavailable');
        }

        $slots = [];
        if ($available) {
            $slots = $this->resolveTransferTimeSlots($car, $date, $passengers);
            if (empty($slots)) {
                $note = __('transfers.booking.availability_no_slots');
            } elseif (!$note) {
                $firstSlot = reset($slots);
                $lastSlot = end($slots);
                if ($firstSlot && $lastSlot && isset($firstSlot['label'], $lastSlot['label'])) {
                    $note = __('transfers.booking.available_hours_range', [
                        'start' => $firstSlot['label'],
                        'end' => $lastSlot['label'],
                    ]);
                }
            }
        }

        return [
            'date' => $date->toDateString(),
            'available' => $available,
            'time_slots' => $slots,
            'note' => $note,
        ];
    }

    protected function resolveTransferTimeSlots(Car $car, Carbon $date, int $passengers): array
    {
        $explicitSlots = $this->getExplicitTimeSlots($car, $date, $passengers);
        $baseSlots = !empty($explicitSlots)
            ? $explicitSlots
            : $this->generateTimeSlotsFromAvailability($car, $date, $passengers);
        if (empty($baseSlots)) {
            $baseSlots = $this->generateBaseTimeSlots($car, $date);
        }
        if (empty($baseSlots)) {
            return [];
        }

        $takenTimes = $this->getTakenTransferTimes($car, $date);
        if (empty($takenTimes)) {
            return $baseSlots;
        }

        $takenLookup = array_flip($takenTimes);
        $availableSlots = [];
        foreach ($baseSlots as $slot) {
            if (!isset($takenLookup[$slot['value']])) {
                $availableSlots[] = $slot;
            }
        }

        return $availableSlots;
    }

    protected function getExplicitTimeSlots(Car $car, Carbon $date, int $passengers): array
    {
        $start = $date->copy()->startOfDay();
        $end = $date->copy()->endOfDay();
        $ranges = $car->getDatesInRange(
            $start->format('Y-m-d H:i:s'),
            $end->format('Y-m-d H:i:s')
        );

        $rangeCollection = $ranges instanceof \Illuminate\Support\Collection
            ? $ranges
            : collect($ranges);

        if ($rangeCollection->isEmpty()) {
            return [];
        }

        $authorId = $car->author_id ? (int) $car->author_id : null;
        $prioritisedRanges = $rangeCollection
            ->groupBy(function ($item) {
                try {
                    return Carbon::parse($item->start_date)->toDateString();
                } catch (\Throwable $exception) {
                    return null;
                }
            })
            ->filter(function ($group, $key) {
                return $key !== null;
            })
            ->map(function ($group) use ($authorId) {
                if ($authorId !== null) {
                    $vendorMatch = $group->first(function ($item) use ($authorId) {
                        return (int) ($item->create_user ?? 0) === $authorId;
                    });
                    if ($vendorMatch) {
                        return $vendorMatch;
                    }
                }
                return $group->first();
            })
            ->filter();

        if ($prioritisedRanges->isEmpty()) {
            return [];
        }

        $slots = [];
        foreach ($prioritisedRanges as $range) {
            if (!$range->active) {
                continue;
            }

            $capacity = is_numeric($range->number) ? (int) $range->number : null;
            if ($capacity !== null) {
                if ($capacity <= 0) {
                    continue;
                }
                if ($capacity < $passengers) {
                    continue;
                }
            }

            $hours = $this->normalizeAvailableHours($range->available_hours ?? null);
            if (empty($hours)) {
                continue;
            }

            $startBoundary = $range->available_start;
            $endBoundary = $range->available_end;

            foreach ($hours as $hour) {
                if ($startBoundary && strcmp($hour, $startBoundary) < 0) {
                    continue;
                }
                if ($endBoundary && strcmp($hour, $endBoundary) > 0) {
                    continue;
                }
                $slots[$hour] = [
                    'value' => $hour,
                    'label' => $hour,
                    'disabled' => false,
                ];
            }
        }

        if (empty($slots)) {
            return [];
        }

        ksort($slots);

        return array_values($slots);
    }

    protected function generateTimeSlotsFromAvailability(Car $car, Carbon $date, int $passengers): array
    {
        $windows = $this->getAvailabilityWindows($car, $date, $passengers);
        if (empty($windows)) {
            return [];
        }

        $step = (int) setting_item('car_transfer_time_step', 30);
        if ($step <= 0) {
            $step = 30;
        }

        $values = [];
        $maxIterations = (int) ceil((24 * 60) / max($step, 1)) + 2;
        foreach ($windows as $window) {
            $start = $window['start']->copy()->second(0);
            $end = $window['end']->copy()->second(0);
            if ($end->lt($start)) {
                continue;
            }

            $cursor = $start->copy();
            $iteration = 0;
            while ($cursor->lte($end) && $iteration <= $maxIterations) {
                $value = $cursor->format('H:i');
                if (!in_array($value, $values, true)) {
                    $values[] = $value;
                }
                $cursor->addMinutes($step);
                $iteration++;
            }
        }

        sort($values);

        return array_map(function ($value) {
            return [
                'value' => $value,
                'label' => $value,
                'disabled' => false,
            ];
        }, $values);
    }

    protected function getAvailabilityWindows(Car $car, Carbon $date, int $passengers): array
    {
        $start = $date->copy()->startOfDay();
        $end = $date->copy()->endOfDay();
        $dailyStart = $this->parseTimeOfDay($car->transfer_time_start, $date);
        $dailyEnd = $this->parseTimeOfDay($car->transfer_time_end, $date);
        $ranges = $car->getDatesInRange(
            $start->format('Y-m-d H:i:s'),
            $end->format('Y-m-d H:i:s')
        );

        if ($ranges instanceof \Illuminate\Support\Collection) {
            if ($ranges->isEmpty()) {
                return [];
            }
        } elseif (empty($ranges)) {
            return [];
        }

        $windows = [];
        foreach ($ranges as $range) {
            if (!$range->active) {
                continue;
            }

            $capacity = is_numeric($range->number) ? (int) $range->number : null;
            if ($capacity !== null) {
                if ($capacity <= 0) {
                    continue;
                }
                if ($capacity < $passengers) {
                    continue;
                }
            }

            if (empty($range->start_date) || empty($range->end_date)) {
                continue;
            }

            try {
                $startTime = Carbon::parse($range->start_date)->setTimezone('Asia/Tbilisi');
                $endTime = Carbon::parse($range->end_date)->setTimezone('Asia/Tbilisi');
            } catch (\Exception $exception) {
                continue;
            }

            if ($endTime->lt($startTime)) {
                continue;
            }

            if ($startTime->lt($start)) {
                $startTime = $start->copy();
            }
            if ($endTime->gt($end)) {
                $endTime = $end->copy();
            }
            if ($dailyStart && $startTime->lt($dailyStart)) {
                $startTime = $dailyStart->copy();
            }
            if ($dailyEnd && $endTime->gt($dailyEnd)) {
                $endTime = $dailyEnd->copy();
            }
            if ($endTime->lt($startTime)) {
                continue;
            }

            $windows[] = [
                'start' => $startTime,
                'end' => $endTime,
            ];
        }

        return $windows;
    }

    protected function generateBaseTimeSlots(Car $car, Carbon $date): array
    {
        $step = (int) setting_item('car_transfer_time_step', 30);
        if ($step <= 0) {
            $step = 30;
        }

        $startSetting = $car->transfer_time_start ?: setting_item('car_transfer_time_start', '00:00');
        $endSetting = $car->transfer_time_end ?: setting_item('car_transfer_time_end', '23:30');

        $startTime = $this->parseTimeOfDay($startSetting, $date) ?: Carbon::createFromTime(0, 0, 0, 'Asia/Tbilisi');
        $endTime = $this->parseTimeOfDay($endSetting, $date) ?: Carbon::createFromTime(23, 30, 0, 'Asia/Tbilisi');

        $start = $date->copy()->setTime($startTime->hour, $startTime->minute, 0);
        $end = $date->copy()->setTime($endTime->hour, $endTime->minute, 0);
        if ($end->lt($start)) {
            if ($car->transfer_time_start && $car->transfer_time_end) {
                return [];
            }
            $end = $start->copy()->endOfDay();
        }

        $values = [];
        $cursor = $start->copy();
        $maxIterations = (int) ceil((24 * 60) / max($step, 1)) + 2;
        $iteration = 0;
        while ($cursor->lte($end) && $iteration <= $maxIterations) {
            $value = $cursor->format('H:i');
            if (!in_array($value, $values, true)) {
                $values[] = $value;
            }
            $cursor->addMinutes($step);
            $iteration++;
        }

        return array_map(function ($value) {
            return [
                'value' => $value,
                'label' => $value,
                'disabled' => false,
            ];
        }, $values);
    }

    protected function getTakenTransferTimes(Car $car, Carbon $date): array
    {
        $bookingIds = Booking::query()
            ->where('object_id', $car->id)
            ->where('object_model', 'car')
            ->whereNotIn('status', Booking::$notAcceptedStatus)
            ->whereDate('start_date', $date->toDateString())
            ->pluck('id');

        if ($bookingIds->isEmpty()) {
            return [];
        }

        $metaValues = DB::table('bravo_booking_meta')
            ->whereIn('booking_id', $bookingIds->all())
            ->where('name', 'transfer_datetime')
            ->pluck('val');

        $times = [];
        foreach ($metaValues as $value) {
            if (!$value) {
                continue;
            }
            try {
                $parsed = Carbon::parse($value, 'Asia/Tbilisi')->setTimezone('Asia/Tbilisi');
                $times[] = $parsed->format('H:i');
            } catch (\Exception $exception) {
                continue;
            }
        }

        return array_values(array_unique($times));
    }

    protected function parseTimeOfDay($value, Carbon $date): ?Carbon
    {
        if ($value === null || $value === '') {
            return null;
        }

        $formats = ['H:i:s', 'H:i'];
        foreach ($formats as $format) {
            try {
                $time = Carbon::createFromFormat($format, (string) $value, 'Asia/Tbilisi');
                return $date->copy()->setTime($time->hour, $time->minute, 0);
            } catch (\Exception $exception) {
                continue;
            }
        }

        return null;
    }

    protected function normalizeAvailableHours($hours): array
    {
        if (is_string($hours)) {
            $decoded = json_decode($hours, true);
            $hours = json_last_error() === JSON_ERROR_NONE ? $decoded : explode(',', $hours);
        }

        if (!is_array($hours)) {
            return [];
        }

        $valid = [];
        foreach ($hours as $hour) {
            if (!is_string($hour) && !is_numeric($hour)) {
                continue;
            }
            $hourString = trim((string) $hour);
            if ($hourString === '') {
                continue;
            }
            try {
                $formatted = Carbon::createFromFormat('H:i', $hourString, 'Asia/Tbilisi')->format('H:i');
                $valid[$formatted] = $formatted;
            } catch (\Exception $exception) {
                continue;
            }
        }

        if (empty($valid)) {
            return [];
        }

        ksort($valid);

        return array_values($valid);
    }

    public function quote(Request $request, Car $car)
    {
        if ($car->status !== 'publish') {
            return $this->sendError(__('transfers.booking.price_details_unavailable'), [], 404);
        }

        $passengers = (int) $request->input('passengers', 1);
        if ($passengers < 1) {
            $passengers = 1;
        }
        $maxPassengers = (int) ($car->number ?? 0);
        if ($maxPassengers > 0 && $passengers > $maxPassengers) {
            $passengers = $maxPassengers;
        }

        $pickupPayload = $request->input('pickup');
        if (is_string($pickupPayload)) {
            $decodedPickup = json_decode($pickupPayload, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                $pickupPayload = $decodedPickup;
            }
        }
        if (!is_array($pickupPayload)) {
            $pickupPayload = [];
        }

        $pickupLocationId = $request->input('pickup_location_id') ?? Arr::get($pickupPayload, 'id');
        $pickupLocation = null;
        if ($pickupLocationId) {
            $pickupLocation = CarPickupLocation::query()
                ->availableForCar($car)
                ->where('id', $pickupLocationId)
                ->first();
            if ($pickupLocation) {
                $pickupPayload = array_merge($pickupLocation->toFrontendArray(), $pickupPayload);
                $pickupPayload['source'] = Arr::get($pickupPayload, 'source', 'backend');
            }
        }

        $pickupLat = Arr::get($pickupPayload, 'lat');
        $pickupLng = Arr::get($pickupPayload, 'lng');
        if (!is_numeric($pickupLat) || !is_numeric($pickupLng)) {
            return $this->sendError(__('transfers.form.pickup_coordinates_required'), [], 422);
        }

        $dropoff = $request->input('dropoff', []);
        if (is_string($dropoff)) {
            $decodedDropoff = json_decode($dropoff, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                $dropoff = $decodedDropoff;
            }
        }
        if (!is_array($dropoff)) {
            $dropoff = [];
        }

        $dropoffLat = Arr::get($dropoff, 'lat');
        $dropoffLng = Arr::get($dropoff, 'lng');
        $dropoffPlaceId = Arr::get($dropoff, 'place_id');
        if (!is_numeric($dropoffLat) || !is_numeric($dropoffLng) || empty($dropoffPlaceId)) {
            return $this->sendError(__('transfers.form.dropoff_coordinates_required'), [], 422);
        }

        $userPickup = $request->input('user_pickup', []);
        if (is_string($userPickup)) {
            $decodedUserPickup = json_decode($userPickup, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                $userPickup = $decodedUserPickup;
            }
        }
        if (!is_array($userPickup)) {
            $userPickup = [];
        }

        $userPickupLat = Arr::get($userPickup, 'lat');
        $userPickupLng = Arr::get($userPickup, 'lng');
        $userPickupPlaceId = Arr::get($userPickup, 'place_id');

        $transferDatetime = $request->input('transfer_datetime');
        $transferDate = null;
        if ($transferDatetime) {
            try {
                $transferDate = Carbon::parse($transferDatetime, 'Asia/Tbilisi')->setTimezone('Asia/Tbilisi')->toDateString();
            } catch (\Exception $exception) {
                $transferDate = null;
            }
        } elseif ($request->filled('transfer_date') && $request->filled('transfer_time')) {
            try {
                $transferDatetime = Carbon::parse($request->input('transfer_date') . ' ' . $request->input('transfer_time'), 'Asia/Tbilisi')
                    ->setTimezone('Asia/Tbilisi')
                    ->toIso8601String();
                $transferDate = Carbon::parse($transferDatetime, 'Asia/Tbilisi')->setTimezone('Asia/Tbilisi')->toDateString();
            } catch (\Exception $exception) {
                $transferDatetime = null;
                $transferDate = null;
            }
        }

        $normalizedPickup = array_merge($pickupPayload, [
            'lat' => (float) $pickupLat,
            'lng' => (float) $pickupLng,
        ]);

        $normalizedDropoff = array_merge($dropoff, [
            'lat' => (float) $dropoffLat,
            'lng' => (float) $dropoffLng,
        ]);

        $routeMetrics = $car::resolveRouteMetrics($normalizedPickup, $normalizedDropoff);

        $normalizedUserPickup = null;
        if (is_numeric($userPickupLat) && is_numeric($userPickupLng)) {
            $normalizedUserPickup = array_merge($userPickup, [
                'lat' => (float) $userPickupLat,
                'lng' => (float) $userPickupLng,
            ]);
        }

        $userRouteMetrics = null;
        if ($normalizedUserPickup) {
            $userRouteMetrics = $car::resolveRouteMetrics($normalizedUserPickup, $normalizedDropoff);
        }

        $normalizedUserPickup = null;
        if (is_numeric($userPickupLat) && is_numeric($userPickupLng)) {
            $normalizedUserPickup = array_merge($userPickup, [
                'lat' => (float) $userPickupLat,
                'lng' => (float) $userPickupLng,
            ]);
        }

        $pricingMode = $car->pricing_mode ?: 'per_km';
        if ($pricingMode !== 'fixed') {
            if (!$normalizedUserPickup || empty($userPickupPlaceId)) {
                return $this->sendError(__('transfers.form.pickup_coordinates_required'), [], 422);
            }
        }

        $userRouteMetrics = null;
        if ($normalizedUserPickup) {
            $userRouteMetrics = $car::resolveRouteMetrics($normalizedUserPickup, $normalizedDropoff);
        }

        $normalizedUserPickup = null;
        if (is_numeric($userPickupLat) && is_numeric($userPickupLng)) {
            $normalizedUserPickup = array_merge($userPickup, [
                'lat' => (float) $userPickupLat,
                'lng' => (float) $userPickupLng,
            ]);
        }

        $pricingMode = $car->pricing_mode ?: 'per_km';
        if ($pricingMode !== 'fixed') {
            if (!$normalizedUserPickup || empty($userPickupPlaceId)) {
                return $this->sendError(__('transfers.form.pickup_coordinates_required'), [], 422);
            }
        }

        $userRouteMetrics = null;
        if ($normalizedUserPickup) {
            $userRouteMetrics = $car::resolveRouteMetrics($normalizedUserPickup, $normalizedDropoff);
        }

        $normalizedUserPickup = null;
        if (is_numeric($userPickupLat) && is_numeric($userPickupLng)) {
            $normalizedUserPickup = array_merge($userPickup, [
                'lat' => (float) $userPickupLat,
                'lng' => (float) $userPickupLng,
            ]);
        }

        $pricingMode = $car->pricing_mode ?: 'per_km';
        if ($pricingMode !== 'fixed') {
            if (!$normalizedUserPickup || empty($userPickupPlaceId)) {
                return $this->sendError(__('transfers.form.pickup_coordinates_required'), [], 422);
            }
        }

        $userRouteMetrics = null;
        if ($normalizedUserPickup) {
            $userRouteMetrics = $car::resolveRouteMetrics($normalizedUserPickup, $normalizedDropoff);
        }

        $normalizedUserPickup = null;
        if (is_numeric($userPickupLat) && is_numeric($userPickupLng)) {
            $normalizedUserPickup = array_merge($userPickup, [
                'lat' => (float) $userPickupLat,
                'lng' => (float) $userPickupLng,
            ]);
        }

        $pricingMode = $car->pricing_mode ?: 'per_km';
        if ($pricingMode !== 'fixed') {
            if (!$normalizedUserPickup || empty($userPickupPlaceId)) {
                return $this->sendError(__('transfers.form.pickup_coordinates_required'), [], 422);
            }
        }

        $userRouteMetrics = null;
        if ($normalizedUserPickup) {
            $userRouteMetrics = $car::resolveRouteMetrics($normalizedUserPickup, $normalizedDropoff);
        }

        $car->clearTransferContext();

        $applied = $car->applyTransferContext(
            $pickupLocation,
            $normalizedPickup,
            $normalizedDropoff,
            $routeMetrics['distance_km'] ?? null,
            $routeMetrics['duration_min'] ?? null,
            $transferDate,
            $transferDatetime,
            $passengers,
            $normalizedUserPickup,
            $userRouteMetrics['distance_km'] ?? null,
            $userRouteMetrics['duration_min'] ?? null
        );

        if (!$applied) {
            return $this->sendError(__('transfers.booking.price_details_unavailable'), [], 422);
        }

        $totalPrice = $car->calculated_price;
        $singlePrice = $car->transfer_price_single;
        $quote = [
            'price' => $totalPrice,
            'total_price' => $totalPrice,
            'price_single' => $singlePrice,
            'distance_km' => $car->transfer_distance_km,
            'duration_min' => $car->transfer_duration_min,
            'pricing_mode' => $car->transfer_pricing_mode,
            'unit_price' => $car->transfer_unit_price,
            'base_fee' => $car->transfer_base_fee,
            'passengers' => $car->transfer_passengers,
            'pickup' => $car->transfer_pickup,
            'user_pickup' => $car->transfer_user_pickup,
            'dropoff' => $car->transfer_dropoff,
            'pickup_label' => $car->transfer_pickup_name,
            'dropoff_label' => $car->transfer_dropoff_name,
            'price_formatted' => $totalPrice !== null ? format_money($totalPrice) : null,
            'total_price_formatted' => $totalPrice !== null ? format_money($totalPrice) : null,
            'price_single_formatted' => $singlePrice !== null ? format_money($singlePrice) : null,
            'unit_price_formatted' => $car->transfer_unit_price !== null ? format_money($car->transfer_unit_price) : null,
            'base_fee_formatted' => $car->transfer_base_fee !== null ? format_money($car->transfer_base_fee) : null,
            'distance_formatted' => $car->transfer_distance_km !== null ? number_format((float) $car->transfer_distance_km, 2) . ' km' : null,
        ];

        return $this->sendSuccess([
            'data' => [
                'quote' => $quote,
            ],
        ]);
    }

    public function detail(Request $request, $slug)
    {
        $row = $this->carClass::where('slug', $slug)->with(['location','translation','hasWishList','pickupLocations.car'])->first();
        if ( empty($row) or !$row->hasPermissionDetailView()) {
            return redirect('/');
        }
        $translation = $row->translate();
        $car_related = [];
        $location_id = $row->location_id;
        if (!empty($location_id)) {
            $car_related = $this->carClass::where('location_id', $location_id)->where("status", "publish")->take($this->limitRelated ?? 4)->whereNotIn('id', [$row->id])->with(['location','translation','hasWishList'])->get();
        }
        $review_list = $row->getReviewList();

        $availablePickupLocations = CarPickupLocation::query()
            ->with(['car:id,title'])
            ->availableForCar($row)
            ->orderByRaw("CASE WHEN name IS NULL OR name = '' THEN 1 ELSE 0 END")
            ->orderByRaw("CASE WHEN address IS NULL OR address = '' THEN 1 ELSE 0 END")
            ->orderBy('name')
            ->orderBy('address')
            ->orderBy('id')
            ->get();

        $pickupPayload = $request->input('pickup');
        if (is_string($pickupPayload)) {
            $decodedPickup = json_decode($pickupPayload, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                $pickupPayload = $decodedPickup;
            }
        }
        if (!is_array($pickupPayload)) {
            $pickupPayload = [];
        }

        $selectedPickupLocation = null;
        $pickupLocationId = Arr::get($pickupPayload, 'id') ?? $request->input('pickup_location_id');
        if ($pickupLocationId) {
            $selectedPickupLocation = $availablePickupLocations->firstWhere('id', (int) $pickupLocationId);
            if ($selectedPickupLocation) {
                $pickupPayload = array_merge($selectedPickupLocation->toFrontendArray(), $pickupPayload);
                $pickupPayload['source'] = Arr::get($pickupPayload, 'source', 'backend');
            } else {
                $selectedPickupLocation = null;
            }
        }

        $transferDatetimeRaw = $request->input('transfer_datetime');
        $transferDatetimeDisplay = null;
        $transferDate = null;
        if ($transferDatetimeRaw) {
            try {
                $transferDatetimeDisplay = Carbon::parse($transferDatetimeRaw, 'Asia/Tbilisi')->setTimezone('Asia/Tbilisi');
                $transferDate = $transferDatetimeDisplay->toDateString();
            } catch (\Exception $exception) {
                $transferDatetimeDisplay = null;
                $transferDate = null;
            }
        }

        $dropoff = $request->input('dropoff', []);
        if (is_string($dropoff)) {
            $decodedDropoff = json_decode($dropoff, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                $dropoff = $decodedDropoff;
            }
        }
        if (!is_array($dropoff)) {
            $dropoff = [];
        }

        $userPickup = $request->input('user_pickup', []);
        if (is_string($userPickup)) {
            $decodedUserPickup = json_decode($userPickup, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                $userPickup = $decodedUserPickup;
            }
        }
        if (!is_array($userPickup)) {
            $userPickup = [];
        }

        $pickupLat = isset($pickupPayload['lat']) && is_numeric($pickupPayload['lat']) ? (float) $pickupPayload['lat'] : null;
        $pickupLng = isset($pickupPayload['lng']) && is_numeric($pickupPayload['lng']) ? (float) $pickupPayload['lng'] : null;
        $dropoffLat = isset($dropoff['lat']) && is_numeric($dropoff['lat']) ? (float) $dropoff['lat'] : null;
        $dropoffLng = isset($dropoff['lng']) && is_numeric($dropoff['lng']) ? (float) $dropoff['lng'] : null;
        $userPickupLat = isset($userPickup['lat']) && is_numeric($userPickup['lat']) ? (float) $userPickup['lat'] : null;
        $userPickupLng = isset($userPickup['lng']) && is_numeric($userPickup['lng']) ? (float) $userPickup['lng'] : null;
        $userPickupPayload = null;
        if ($userPickupLat !== null && $userPickupLng !== null) {
            $userPickupPayload = array_merge($userPickup, [
                'lat' => $userPickupLat,
                'lng' => $userPickupLng,
            ]);
        }
        $passengers = (int) $request->input('number', 1);
        if ($passengers < 1) {
            $passengers = 1;
        }
        if ($pickupLat !== null && $pickupLng !== null && $dropoffLat !== null && $dropoffLng !== null) {
            $normalizedPickup = array_merge($pickupPayload, ['lat' => $pickupLat, 'lng' => $pickupLng]);
            $metrics = $this->carClass::resolveRouteMetrics($normalizedPickup, $dropoff);
            $userRouteMetrics = null;
            if ($userPickupPayload) {
                $userRouteMetrics = $this->carClass::resolveRouteMetrics($userPickupPayload, $dropoff);
            }
            $routePickupLocation = $selectedPickupLocation;
            $pricingMode = $row->pricing_mode ?: 'per_km';
            $shouldApply = true;
            if ($pricingMode !== 'fixed' && !$userPickupPayload) {
                $shouldApply = false;
            }
            if ($shouldApply) {
                $row->applyTransferContext(
                    $routePickupLocation,
                    $normalizedPickup,
                    $dropoff,
                    $metrics['distance_km'],
                    $metrics['duration_min'],
                    $transferDate,
                    $transferDatetimeRaw,
                    $passengers,
                    $userPickupPayload,
                    $userRouteMetrics['distance_km'] ?? null,
                    $userRouteMetrics['duration_min'] ?? null
                );
            }
        }

        $data = [
            'row'          => $row,
            'translation'       => $translation,
            'car_related' => $car_related,
            'booking_data' => $row->getBookingData(),
            'review_list'  => $review_list,
            'seo_meta'  => $row->getSeoMetaWithTranslation(app()->getLocale(),$translation),
            'body_class'=>'is_single',
            'pickup_location' => $selectedPickupLocation,
            'pickup_payload' => $pickupPayload,
            'dropoff' => $dropoff,
            'user_pickup' => $userPickup,
            'user_pickup_payload' => $userPickupPayload,
            'transfer_datetime_value' => $transferDatetimeRaw,
            'transfer_datetime_display' => $transferDatetimeDisplay,
            'transfer_distance_km' => $row->transfer_distance_km,
            'pickup_locations' => $availablePickupLocations,
            'breadcrumbs'       => [
                [
                    'name'  => __('Car'),
                    'url'  => route('car.search'),
                ],
            ],
        ];
        $data['breadcrumbs'] = array_merge($data['breadcrumbs'],$row->locationBreadcrumbs());
        $data['breadcrumbs'][] = [
            'name'  => $translation->title,
            'class' => 'active'
        ];
        $this->setActiveMenu($row);
        return view('Car::frontend.detail', $data);
    }
}
